version: "3.3"

services:
  openeocubes:
    build: .
    environment:
      - TZ=Etc/UTC
      - DEBIAN_FRONTEND=noninteractive
      - AWSHOST=
    container_name: openeocubes
    ports:
      - "8000:8000"
    restart: always
